import Head from "next/head"
import React from "react"
import Details from "./Details"
import MyModal from "./MyModal"
import Sidebar from "./Sidebar"
import ActiveList from "./ActiveList"
import AddItem from "./AddItem"

interface Props {
  children: JSX.Element
}

export default function Layout({ children }: Props) {
  return (
    <main className="h-screen w-screen bg-[#FAFAFE] flex">
      <Head>
        <title>Shoppingify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyModal />
      <Sidebar />

      <section className="flex-grow h-full py-14 px-32 overflow-scroll hideScrollbar">
        {children}
      </section>

      <ActiveList />
      {/* <AddItem /> */}
      {/* <Details /> */}
    </main>
  )
}
